name: ExtDN M2 Integration Tests
on: [ push, pull_request ]

jobs:
  integration:
    uses: customgento/m2-github-actions/.github/workflows/integration.yml@main
    with:
      module_name: EasyTranslate_CompatMageplazaBlog
      composer_name: easytranslate/m2-compat-mageplaza-blog
